name: Build Qio and push to GAR

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: rainbowq
  REGION: us-west2
  GAR_LOCATION: us-west2-docker.pkg.dev/rainbowq/bows/
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: qio-cli

jobs:
  push-build-artifact:
    name: Upload Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Docker auth"
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Get tag"
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: "Build image"
        run: |-
          docker build -t ${{ env.IMAGE }}_${{ steps.get-tag.outputs.short_ref }} \
          --build-arg GITHUB_SHA=${{ github.sha }} \
          --build-arg GITHUB_REF=${{ github.ref }} .

      - name: "Push image"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |-
            ${{ env.GAR_LOCATION }}${{ env.IMAGE }}:${{ steps.get-tag.outputs.short_ref }}
            ${{ env.GAR_LOCATION }}${{ env.IMAGE }}:latest
