name: Build Qio and push to GAR

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: rainbowq
  REGION: us-west2
  GAR_LOCATION: us-west2-docker.pkg.dev/rainbowq/bows/
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: qio

jobs:
  push-build-artifact:
    name: Upload Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: "Build image"
        run: |-
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'` && echo $TAG
          docker build -t "${IMAGE}_${TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" .

      - name: "Push image"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${GAR_LOCATION}${IMAGE}:${TAG}
            ${GAR_LOCATION}${IMAGE}:latest
