name: Build Qio CLI and push to GAR

on:
  push:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: qio

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry Repo
    runs-on: ubuntu-latest
    # only upload if the push is tagged
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/359816952063/locations/global/workloadIdentityPools/rainpool/providers/github-provider
          service_account: rainbowqio@rainbowq.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
             us-west2-docker.pkg.dev/359816952063/bows/${IMAGE}-cli:${{ steps.get-tag.outputs.short_ref }}
             us-west2-docker.pkg.dev/359816952063/bows/${IMAGE}-cli:latest

