name: Push to Docker Hub

on:
  push:
    branches:
      - 'main'

        #env:
        #  GITHUB_REF: ${{ github.ref }}
        #  GITHUB_SHA: ${{ github.sha }}
        #  IMAGE: qio

jobs:
  build-n-push:
    name: Upload Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    steps:
      #      - id: tokenDEBUG
        #        run: |
        #          if ! [[ -z "${{ secrets.GHA_TOKEN }}" ]]; then
        #            echo ::set-output has_token=true
        #          else
        #            echo ::set-output has_token=false
        #          fi
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Docker meta"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            rainbowq/qio
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "DEBUG Values"
        run: ${{ steps.meta.outputs.tags }}

      - name: "Build and push"
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
