name: Build Qio CLI and push to GCR

on:
  push:
    tags:
      - 0.0.*

# Environment variables available to all jobs and steps in this workflow
#  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
#  GKE_KEY: ${{ secrets.GKE_KEY }}
env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: qio
  RHOST: gcr.io
  PROJECT: ${{ secrets.GCP_PROJECT }}


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCR_KEY }}
        export_default_credentials: true

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'` && echo $TAG
        docker build -t "${IMAGE}_${TAG}" \
          --build-arg GITHUB_SHA="${GITHUB_SHA}" \
          --build-arg GITHUB_REF="${GITHUB_REF}" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'` && echo $TAG
        # First tag and push the version
        docker tag "${IMAGE}_${TAG}" "$RHOST"/"$PROJECT"/"$IMAGE":"$TAG"
        docker push "$RHOST"/"$PROJECT"/"$IMAGE":"$TAG"
        # Then tag this as 'latest'
        docker tag "$RHOST"/"$PROJECT"/"$IMAGE":"$TAG" "$RHOST"/"$IMAGE":latest
        docker push "$RHOST"/"$PROJECT"/"$IMAGE":latest
